### ISSUE TITLE
Can't find references of the contents of an inline function

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#184]
## Description

Trying to find references to the GenServer module located at the cursor will not work, as it thinks you are trying to find references to the function definition of Cache.get/0

```elixir
    defmodule Cache do
      use GenServer

      def get(), do: GenServer.call(__MODULE__, :get)
      #                 ^
    end
```

## Acceptance Criteria

it should find references to the symbol under the cursor

**Comment by TwistingTwists** [comment]
I am willing to take this up. Can you please point to which files to look at?

**Comment by mhanberg** [comment]
@TwistingTwists hi!

I believe someone else has started on this, but I'll confirm with them if they've made progress.

**Comment by mhanberg** [comment]
@apoorv_2204 can I assign this to you?

**Comment by apoorv-2204** [comment]
> @apoorv-2204 can I assign this to you?

Sure

**Comment by apoorv-2204** [comment]
How to reproduce this error?

**Comment by mhanberg** [comment]
@apoorv-2204  you should be able to use the code snippet above and follow the instructions in order to reproduce

**Comment by mhanberg** [comment]
@TwistingTwists I think you can tackle this if you're still interested!

**Comment by TwistingTwists** [comment]
> I am willing to take this up. Can you please point to which files to look at?

Aye aye captain. Point me to the files I need to look !

**Comment by apoorv-2204** [comment]
> > I am willing to take this up. Can you please point to which files to look at?
> 
> Aye aye captain. Point me to the files I need to look !

maybe its is generating that code, as for cache , whenever it is going through any code base.
or either when ls is reading any new repo or code, its not recognising the call.

**Comment by mhanberg** [comment]
> > I am willing to take this up. Can you please point to which files to look at?
> 
> 
> 
> Aye aye captain. Point me to the files I need to look !

lib/next_ls.ex

**Comment by mhanberg** [comment]
@TwistingTwists i think the primary problem is somewhere a query is being made or something that is only accounting for the line number and not also the column number

**Comment by TwistingTwists** [comment]
That is a good head start for me. I will familiarise my self with the codebase and ask more questions as I explore more

**Comment by mhanberg** [comment]
Awesome, thanks!

**Comment by crbelaus** [comment]
Is this still a problem? In my case it seems to work well as it is looking references for `Genserver` instead of the `get` function.

<details><summary>This looks for references of `Genserver`</summary>

<img width="500" alt="image" src="https://github.com/elixir-tools/next-ls/assets/2965623/4077340e-c1a5-408d-95a9-ea4ca60ba825">
</details>

<details><summary>This looks for references of `get`</summary>

<img width="488" alt="image" src="https://github.com/elixir-tools/next-ls/assets/2965623/d56fff15-baed-4680-a899-4317c006b884">
</details>

**Comment by mhanberg** [comment]
Interesting, let me check locally

**Comment by mhanberg** [comment]
Oh, I think VScode is giving you those hints. 

Add a reference to the get function somewhere and try that

**Comment by crbelaus** [comment]
Oh I see now. You are right!

I think that I know how to fix this. Let me check if I'm correct and open a PR.

**Comment by crbelaus** [comment]
When we check what's under the cursor we always get the function that's defined in that line because, as you point out, we are not taking the cursor column into account ([link](https://github.com/elixir-tools/next-ls/blob/a27d3f431d8b21caa2804c8058b3df4700384684/lib/next_ls.ex#L944-L950)).

My first thought was to modify the query to take the line into account just like we do when querying the `references` table. Unfortunately there seems to be another issue in the `symbols` table which is that every definition has the correct line but they column is always 1.

I think that we should:
1. Update the `symbols` table to have a `start_column` and `end_column` just like the `references` table.
2. Update the previously linked query to take the `start_column` and `end_column` so the language server knows that the cursor is not under the function definition but on a different function call.

Next question is how to proceed for a migration in the `symbols` table?

**Comment by mhanberg** [comment]
To get the column information, we'll need to do some AST analyzing or ask José on the forum how to get the column info in the compilation tracer event. 

I prefer the latter, as it'll be the easiest. 

If it needs a fix to elixir core, then I'm okay with fixing it and just having it be a progressive enhancement as folks update their elixir versions. 

Re: José, it's tempting to just mention him here on GitHub, but I prefer to go through his preferred channels (the forum) for questions, to respect his time. 

I can post a question when I get home.

**Comment by crbelaus** [comment]
I agree with you @mhanberg. Asking José sounds like the best course of action.
I took a look at the AST but it did not seem clear how to extract the column information from there.

**Comment by mhanberg** [comment]
https://elixirforum.com/t/how-to-find-function-clause-column-information/59177

cc @crbelaus we'll see what José says

**Comment by mhanberg** [comment]
https://github.com/elixir-lang/elixir/issues/13029

**Comment by crbelaus** [comment]
Cool I believe we can get the available column information for newest Elixir versions and just fall back to line 1 like we do now for older versions 👍
